apiVersion: batch/v1
kind: Job
metadata:
  name: boletimcovid
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: boletimcovidv2
        image: arturrogerio/boletimcovid:v2
        # a tag command somente é necessária se for para substituir o comando existente no dockerfile
        command: ["python", "/run.py"]
      restartPolicy: Never